
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('1', 'AC', 'Acre');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('2', 'AL', 'Alagoas');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('3', 'AP', 'Amapá');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('4', 'AM', 'Amazonas');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('5', 'BA', 'Bahia');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('6', 'CE', 'Ceará');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('7', 'DF', 'Distrito Federal');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('8', 'ES', 'Espírito Santo');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('9', 'GO', 'Goiás');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('10', 'MA', 'Maranhão');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('11', 'MT', 'Mato Grosso');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('12', 'MS', 'Mato Grosso do Sul');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('13', 'MG', 'Minas Gerais');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('14', 'PA', 'Pará');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('15', 'PB', 'Paraíba');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('16', 'PR', 'Paraná');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('17', 'PE', 'Pernambuco');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('18', 'PI', 'Piauí');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('19', 'RJ', 'Rio de Janeiro');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('20', 'RN', 'Rio Grande do Norte');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('21', 'RS', 'Rio Grande do Sul');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('22', 'RO', 'Rondônia');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('23', 'RR', 'Roraima');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('24', 'SC', 'Santa Catarina');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('25', 'SP', 'São Paulo');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('26', 'SE', 'Sergipe');
INSERT INTO Estado (`id`, `sigla`, `descricao`) VALUES ('27', 'TO', 'Tocantins');